server {
    listen 443 ssl;
    server_name localhost;

    # Ajusta las rutas si usas certificados SSL locales o autofirmados
    ssl_certificate /etc/nginx/certs/cert.crt;
    ssl_certificate_key /etc/nginx/certs/cert.key;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}