server:
  port: 0
  address: 0.0.0.0

spring:
  application:
    name: pago-service
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:localhost:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  cloud:
    config:
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: false
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true