server:
  port: 8086
  address: 0.0.0.0

spring:
  application:
    name: producto-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/8680c901-cdee-41fb-b489-95b35c8ffaf0/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/8680c901-cdee-41fb-b489-95b35c8ffaf0/v2.0
  datasource:
    # Cambiar 'bd_producto' por la base de datos correspondiente a cada servicio
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_producto}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    config:
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: false
    loadbalancer:
      enabled: true
  # ¡Aquí mismo anidamos la conexión a RabbitMQ dentro de spring!
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    instance-id: \({spring.application.name}:\){random.value}
    prefer-ip-address: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    clean-on-validation-error: true

# Y aquí abajito dejamos las colas y exchanges personalizados (fuera de spring)
rabbitmq:
  exchanges:
    principal: "cloudnative.exchange"
  queues:
    notificaciones: "notificaciones.queue"
    tickets: "tickets.queue"
    dlq: "cloudnative.dlq"
  routing-keys:
    notificaciones: "routing.notificaciones"
    tickets: "routing.tickets"
    dlq: "routing.dlq"