server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-microservicios/
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Esto va fuera de 'spring' porque es una configuración propia nuestra (custom)
rabbitmq:
  exchanges:
    principal: "cloudnative.exchange"
  queues:
    notificaciones: "notificaciones.queue"
    tickets: "tickets.queue"
    dlq: "cloudnative.dlq"
  routing-keys:
    notificaciones: "routing.notificaciones"
    tickets: "routing.tickets"
    dlq: "routing.dlq"