server:
  port: 8083

spring:
  application:
    name: mensajeria-service
  rabbitmq:
    addresses: rabbitmq1:5672,rabbitmq2:5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/